- datapackage/datapackage.py
- datapackage/registry.py
- tests/test_registry.py
Fixes #30 
I've changed my mind about how to handle exceptions. I think we should wrap the exceptions in most cases. This way, the user can do something like:
```python
import datapackage
try:
dp = datapackage.DataPackage('datapackage.json')
except datapackage.exceptions.RegistryError:
except datapackage.exceptions.SchemaError:
except datapackage.exceptions.DataPackageException:
```
Or, if she doesn't care on the type of exception, she could just catch `datapackage.exceptions.DataPackageException`. The only exceptions that don't inherit from `DataPackageException` are the ones related to the data. For example:
```python
try:
dp.resources[0].data
except IOError:
except ValueError:
```
These exceptions are consistent with the rest of Python ecosystem when loading/parsing data, so I think …
> Improve exceptions

- tests/conftest.py
- tests/test_datapackage.py
- tests/test_resource.py
@pwalsh This encapsulates tempfile creation, so if we have some issue with py3 we just need to fix in one place.
> Extract tempfile creation to fixtures in tests

- README.md
- datapackage/registry.py
- tests/test_registry.py
This allows users to use the latest schemas from the official registry without
having to hardcode its URL in their code. Currently it points to
'http://schemas.datapackages.org/registry.csv'.
Fixes #48 
cc @pwalsh
> [#48] Adds Registry.REGISTRY_DEFAULT_URL pointing to the official registry

- .travis.yml
- README.md
- appveyor.yml
Originally I wanted to enable CI on OSX as well, but Travis doesn't support Python + OSX out of the box. (see https://github.com/travis-ci/travis-ci/issues/2312). There're workarounds, which I think we should do later (issue #61), but I didn't want to spend more time on this issue now. This fixes #60.
> Enable CI on Windows

- .venv
- README.md
- datapackage/__init__.py
- datapackage/helpers.py
- datapackage/mappers.py
- datapackage/pushpull.py
- setup.py
- tests/fixtures/datapackage/data.csv
- tests/fixtures/datapackage/datapackage.json
- tests/test_helpers.py
- tests/test_mappers.py
- tests/test_pushpull.py
Work in progress will wait a discussion and https://github.com/frictionlessdata/testsuite-py tests added and passed.
> [WIP] added push_datapackage and pull_datapackage

- datapackage/pushpull.py
Some engines like [Python Pandas](https://github.com/frictionlessdata/jsontableschema-pandas-py) keeps data in memory and uses Storage as a container for data stored in memory.
In order to access that data, storage instance has to be returned.
See: https://github.com/frictionlessdata/datapackage-py/issues/73
> Return storage object after push/pull

- README.md
- datapackage/datapackage.py
- datapackage/pushpull.py
- datapackage/resource.py
- tests/test_datapackage.py
- tests/test_pushpull.py
- tests/test_resource.py
Fixes #88.
@vitorbaptista @roll @amercader @akariv for review.
> Use descriptor, not metadata, to stay close to spec semantics.

- datapackage/resource.py
- tests/test_pushpull.py
- tests/test_resource.py
> Cast proper types when loading resource data

- datapackage/resource.py
- tests/test_datapackage.py
This fixes #97 by setting the `local_data_path` of a relative source in a remote package to `None`.
> nullify local_data_path of relative source in remote package

- CONTRIBUTORS
- datapackage/schemas/definitions.json
- datapackage/schemas/json-table-schema.json
Hey all - per the most recent change to the spec noted at http://specs.frictionlessdata.io/json-table-schema/ , `gyear` and `gyearmonth` should be valid types for datapackage validation - this PR adds both of those types to the schema file.
> added gyear and gyearmonth types to type enum for validation, per spec

- datapackage/config.py
- datapackage/datapackage.py
- tests/conftest.py
- tests/test_datapackage.py
- tests/test_pushpull.py
- connects #131
- apply defaults (profile, resource.profile, resource.encoding, resource.dialect, resource.schema)
---
For now I don't use automated method from `jsonschema` package for `tableschema` and `datapackage` - http://python-jsonschema.readthedocs.io/en/latest/faq/#why-doesn-t-my-schema-that-has-a-default-property-actually-set-the-default-on-my-instance
There are reasons:
- solution seems over-complicated (modifying validation etc)
- not sure is it portable even to javascript (don't want too have two different kind of logic)
- jsonschema still doesn't cover some edge-cases like default field type
So for now solution is pretty simple. Leaving for a future re-estimation jsonschema usage actuality.
> Apply defaults to data package descriptor

- datapackage/config.py
- tests/test_package.py
- tests/test_resource.py
According to the [CSV dialect specification](https://frictionlessdata.io/specs/csv-dialect/), the escapeChar option should not be set by default.
> `escapeChar` - specifies a one-character string to use for escaping (for example, `\`), mutually exclusive with `quoteChar`. Not set by default
Closes #200
Continued from #201
> Remove escapeChar from DEFAULT_DIALECT

- README.md
- datapackage/profile.py
In the `README.md`, keyword arguments of some classes and methods are
incorrectly displayed as positional arguments.
Conversely, the positional argument of `profile.validate` should be
`descriptor` (as stated in the `README.md`), not `data` (as it is in
`datapackage/profile.py`).
> Use correct keyword and positional arguments

- datapackage/package.py
According to the [documentation](https://github.com/frictionlessdata/datapackage-py#packagesavetarget-storagenone-options), save should prioritize saving to storage over
saving to json.
> `package.save(target, storage=None, **options)`
> Saves this data package to storage if storage argument is passed or saves this data package's descriptor to json file if target arguments ends with .json or saves this data package to zip file otherwise.
Proritizing saving to storage over saving to json is also consistent with the behaviour of the resource save method.
> Fix save order for Package save method

- datapackage/resource.py
- tests/test_resource.py
Very similar to the way that these options are passed to the `Storage.connect` method,
we now use these options in the `Table` constructor in cases where storage is not used.
> Enable passing options from resource init to get_table

- datapackage/resource.py
- tests/test_resource.py
Resource constructor allows passing options directly to tabulator - however, 'skip_rows' was overwritten by a value from the descriptor.
This change will check for another fallback value, from the provided options.
> Allows skip_rows to be provided in Resource options as well

- datapackage/config.py
- datapackage/resource.py
- follows https://github.com/frictionlessdata/tabulator-py/pull/270
---
Missing parts:
> Added s3 to the remote schemes

- setup.py
Hi. I tried to upgrade to datapackage 1.10.1 but found it is not compatible with Tableschema 1.12.0.
Steps to reproduce:
```
$ pip install datapackage==1.10.1
$ pip install tableschema==1.12.0
$ python3
>>> import datapackage
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/chris/.virtualenvs/datapackage-repro-gwcs1gD0/lib/python3.6/site-packages/datapackage/__init__.py", line 13, in <module>
from .package import Package
File "/home/chris/.virtualenvs/datapackage-repro-gwcs1gD0/lib/python3.6/site-packages/datapackage/package.py", line 20, in <module>
from .resource import Resource
File "/home/chris/.virtualenvs/datapackage-repro-gwcs1gD0/lib/python3.6/site-packages/datapackage/resource.py", line 17, in <module>
from .profile import Profile
File …
```
> Require tableschema>=1.12.1

- datapackage/package.py
When saving as a zip archive, format `datapackage.json` so that it's human readable.
---
Please preserve this line to notify @roll (lead of this repository)
> datapackage/package.py: format json with indent when saving as zip

- datapackage/resource.py
Very simple update to avoid opening  at once all streams of a multipart resource which is unnecessary and causes system issues for large number of chunks.
relates #276 
---
Please preserve this line to notify @roll (lead of this repository)
> use iterator for streams in multipart fixes #246
