datapackage/datapackage.py, datapackage/resource.py, tests/fixtures/datapackage_with_foo.txt_resource.json, tests/test_datapackage.py, tests/test_resource.py
=> Ignore base in metadata

datapackage/schemas/fiscal-data-package.json
f456a23 Merge pull request #45 from dataprotocols/rename-mapping-to-model
c7a2af4 Rename "mapping" to "model"
git-subtree-dir: datapackage/schemas
git-subtree-split: f456a23cad4fe4239ce446a3cff45bbd07db74cb
=> Squashed 'datapackage/schemas/' changes from 1a06ab0..f456a23

datapackage/registry.py, datapackage/resource.py, setup.py
It's prepared to merge when `tabulator-v0.5` with some breaking changes will be release on PyPi. Also it fixes #32. 
**It will fail for now.**
=> Updates for tabulator-v0.5

datapackage/resource.py
=> fixed TabularResource.iter

datapackage/mappers.py, datapackage/pushpull.py, datapackage/registry.py, datapackage/resource.py, setup.py, tests/test_mappers.py, tests/test_pushpull.py
- fixes #58 (added warning)
- fixes #106
- fixes #111
=> Updated to jsontableschema-v0.7

datapackage/resource.py, tests/fixtures/datapackage/data.csv, tests/fixtures/datapackage/datapackage.json
Add support for the full CSV dialect spec and pass the correct options to tabulator.
=> Add full CSV dialect support

datapackage/datapackage.py, datapackage/helpers.py, setup.py, tests/fixtures/csv_dialect.json, tests/fixtures/datapackage_with_dereferencing.json, tests/fixtures/table_schema.json, tests/test_datapackage.py
- connects #131 
-  implement resource.schema and resource.dialect dereferencing
=> Added support for URI dereferencing (schema, dialect)

README.md
=> fix datetime processing

.gitignore, README.md, datapackage/exceptions.py, datapackage/package.py, datapackage/resource.py, datapackage/validate.py, setup.py, tests/test_package.py
- fixes #150 
- improved `validate`
- synced with `tableschema.exceptions.TableSchemaException`
=> Support foreign key checks

README.md, datapackage/exceptions.py, datapackage/package.py, datapackage/profiles/data-package.json, datapackage/profiles/fiscal-data-package.json, datapackage/profiles/tabular-data-package.json, datapackage/profiles/tabular-data-resource.json, datapackage/resource.py, setup.py, tests/test_package.py
- fixes #155
---
Requires https://github.com/frictionlessdata/tableschema-py/pull/189
=> Improved foreign keys API

datapackage/package.py, datapackage/profile.py, datapackage/resource.py, tests/test_resource.py
=> Added deprecated resource.data

datapackage/registry.py
=> [#164] Set encoding in registry open file to 'utf-8'

data/package_dialect_no_header.csv, data/package_dialect_no_header.json, datapackage/resource.py, tests/test_package.py
=> Fixed resource dialect with no header property

datapackage/package.py
=> Don't use to_json whili zipping

examples/package.py, examples/resource.py
=> Added examples

datapackage/cli.py, datapackage/profile.py, tests/test_cli.py
- fixes #169 
---
It's a port of https://github.com/frictionlessdata/tableschema-py/pull/197
=> Improved validation error messages

README.md, datapackage/package.py, datapackage/pushpull.py, datapackage/resource.py, setup.py, tests/test_package.py, tests/test_resource.py
=> Integrated Package/Resource with Storage on specs-v1

datapackage/package.py, tests/test_package.py
=> Fix package.save FK resource naming

data/data.csvformat, datapackage/config.py, datapackage/resource.py, tests/test_resource.py
=> Fixed resource.infer if format is provided

README.md
By looking at the spec, the descriptor MUST be name datapackage.json.
=> Small fix at README.md. 

datapackage/helpers.py, tests/test_package.py
=> Force utf8 encoding for all remote descriptor loads

datapackage/package.py
Thanks @roll 
Think this is what you've asked for? Moved property up to main api.
=> Fixes #216.

README.md, datapackage/exceptions.py, datapackage/helpers.py, datapackage/resource.py, setup.py, tests/test_resource.py
- connects https://github.com/frictionlessdata/tableschema-py/pull/257/files 
---
Please preserve this line to notify @roll (lead of this repository)
=> Added an ability to check tabular resource's integrity

Makefile, README.md, datapackage/__init__.py, datapackage/__main__.py, datapackage/cli.py, datapackage/config.py, datapackage/exceptions.py, datapackage/group.py, datapackage/infer.py, datapackage/package.py, datapackage/profile.py, datapackage/pushpull.py, datapackage/resource.py, datapackage/validate.py, pylama.ini, setup.py, tests/test_cli.py
We rebase on pydoc-markdown which is really close to the almost standard Google docstrings syntax
=> Generate API Reference from docstrings

datapackage/profile.py, tests/test_profile.py
=> Fix profile being loaded from local path (not supported in the specs)

datapackage/package.py, tests/test_package.py
=> Fix legacy `tabular` schema Package initiation without a descriptor

Makefile, README.md, data/table.csv, datapackage/package.py, datapackage/resource.py, tests/test_package.py, tests/test_resource.py
=> Add `unsafe` option to Package and Resource

tests/test_resource.py
=> Added skipRows test
